export const siteData = {
  company: {
    name: "Terramar Náutica",
    tagline: "Mantenimiento y traslado profesional de embarcaciones",
    description: "Cuidamos tu embarcación con experiencia técnica y atención personalizada.",
    phone: "+34 XXX XXX XXX",
    email: "info@terramar-nautica.com",
    address: "Puerto Deportivo, Marina Real, España",
  },

  services: [
    {
      id: "mantenimiento",
      title: "Mantenimiento Preventivo y Correctivo",
      description: "Revisiones periódicas y afinaciones para mantener tu embarcación en perfecto estado.",
      icon: "🔧",
    },
    {
      id: "reparaciones",
      title: "Reparaciones de Motores Marinos",
      description: "Diagnóstico y puesta a punto especializada en Yanmar, Volvo, Cummins y motores fuera de borda.",
      icon: "⚙️",
    },
    {
      id: "logistica",
      title: "Logística y Abastecimiento",
      description: "Gestión completa de repuestos, provisiones y suministros para tu embarcación.",
      icon: "📦",
    },
    {
      id: "traslados",
      title: "Traslados y Pilotaje",
      description: "Traslado seguro y profesional de lanchas, veleros y yates con pilotos certificados.",
      icon: "🚤",
    },
    {
      id: "inspecciones",
      title: "Inspecciones Técnicas y Certificaciones",
      description: "Reportes detallados, checklists técnicos y asesoría especializada.",
      icon: "📋",
    },
    {
      id: "emergencias",
      title: "Asistencia en Ruta / Emergencias",
      description: "Soporte técnico y atención prioritaria las 24 horas.",
      icon: "🆘",
    },
  ],

  cases: [
    {
      id: 1,
      title: "Overhaul Motor Yanmar 4JH5E",
      category: "Reparaciones",
      location: "Marina Valencia",
      description: "Reconstrucción completa de motor diésel con pruebas en mar y certificación.",
      image: "/yacht-engine-repair-workshop.jpg",
      beforeImage: "/damaged-marine-engine.jpg",
      afterImage: "/restored-marine-engine.jpg",
      tags: ["Yanmar", "4JH5E", "Overhaul"],
    },
    {
      id: 2,
      title: "Mantenimiento Preventivo Catamaran Lagoon 42",
      category: "Mantenimiento",
      location: "Puerto Deportivo Alicante",
      description: "Servicio completo de mantenimiento anual con cambio de filtros y fluidos.",
      image: "/catamaran-maintenance-dock.jpg",
      beforeImage: "/catamaran-before-maintenance.jpg",
      afterImage: "/catamaran-after-maintenance.jpg",
      tags: ["Lagoon", "Catamaran", "Preventivo"],
    },
    {
      id: 3,
      title: "Traslado Velero Beneteau Oceanis 45",
      category: "Traslados",
      location: "Mallorca - Barcelona",
      description: "Traslado seguro de velero con equipo profesional y seguro completo.",
      image: "/sailing-yacht-transport-delivery.jpg",
      beforeImage: "/yacht-departure-marina.jpg",
      afterImage: "/yacht-arrival-destination.jpg",
      tags: ["Beneteau", "Oceanis", "Traslado"],
    },
    {
      id: 4,
      title: "Inspección Pre-compra Sunseeker Manhattan 52",
      category: "Inspecciones",
      location: "Puerto Banús",
      description: "Inspección técnica completa para compraventa con informe detallado.",
      image: "/luxury-yacht-inspection-survey.jpg",
      beforeImage: "/yacht-hull-inspection.jpg",
      afterImage: "/yacht-engine-inspection-report.jpg",
      tags: ["Sunseeker", "Inspección", "Pre-compra"],
    },
    {
      id: 5,
      title: "Reparación Sistema Propulsión Volvo Penta D6",
      category: "Reparaciones",
      location: "Marina Ibiza",
      description: "Diagnóstico y reparación de sistema de propulsión con repuestos originales.",
      image: "/volvo-penta-engine-repair-marine.jpg",
      beforeImage: "/faulty-marine-propulsion-system.jpg",
      afterImage: "/repaired-volvo-penta-engine.jpg",
      tags: ["Volvo Penta", "D6", "Propulsión"],
    },
    {
      id: 6,
      title: "Logística Regata Copa del Rey",
      category: "Logística",
      location: "Real Club Náutico Palma",
      description: "Soporte logístico completo para flota de regata con repuestos y asistencia.",
      image: "/placeholder.svg?height=300&width=400",
      beforeImage: "/placeholder.svg?height=200&width=300",
      afterImage: "/placeholder.svg?height=200&width=300",
      tags: ["Regata", "Logística", "Copa del Rey"],
    },
  ],

  plans: [
    {
      id: "basico",
      name: "Básico",
      price: "150€",
      description: "Revisión rápida + afinación menor",
      features: [
        "Inspección visual completa",
        "Revisión de niveles",
        "Afinación básica del motor",
        "Informe de estado",
      ],
    },
    {
      id: "profesional",
      name: "Profesional",
      price: "350€",
      description: "Revisión completa con cambio de filtros",
      features: [
        "Todo lo del plan Básico",
        "Cambio de filtros",
        "Ajuste de carburación/combustible",
        "Revisión sistema eléctrico",
        "Pruebas de funcionamiento",
      ],
      popular: true,
    },
    {
      id: "integral",
      name: "Integral",
      price: "650€",
      description: "Media jornada con diagnóstico completo",
      features: [
        "Todo lo del plan Profesional",
        "Diagnóstico completo con equipos",
        "Pruebas en mar",
        "Informe técnico detallado",
        "Seguimiento post-servicio",
      ],
    },
    {
      id: "medida",
      name: "A Medida",
      price: "Consultar",
      description: "Solución personalizada para tu embarcación",
      features: ["Evaluación personalizada", "Presupuesto detallado", "Servicios específicos", "Atención prioritaria"],
    },
  ],

  testimonials: [
    {
      id: 1,
      name: "Carlos Mendoza",
      role: "Armador - Yacht Club Valencia",
      content:
        "Excelente servicio técnico. Mi Beneteau 45 nunca había funcionado tan bien después del mantenimiento integral.",
      avatar: "/placeholder.svg?height=60&width=60",
    },
    {
      id: 2,
      name: "Marina Rodríguez",
      role: "Propietaria - Lancha Deportiva",
      content: "Profesionales de confianza. El traslado de mi embarcación fue perfecto y sin complicaciones.",
      avatar: "/placeholder.svg?height=60&width=60",
    },
    {
      id: 3,
      name: "Antonio García",
      role: "Capitán - Flota Comercial",
      content: "Respuesta rápida en emergencias y técnicos muy preparados. Recomiendo sus servicios al 100%.",
      avatar: "/placeholder.svg?height=60&width=60",
    },
  ],

  process: [
    {
      step: 1,
      title: "Contacto y Brief Técnico",
      description: "Evaluamos las necesidades específicas de tu embarcación",
    },
    {
      step: 2,
      title: "Planificación y Logística",
      description: "Organizamos el servicio con los recursos necesarios",
    },
    {
      step: 3,
      title: "Intervención Técnica",
      description: "Ejecutamos el trabajo con pruebas en mar si es necesario",
    },
    {
      step: 4,
      title: "Informe y Seguimiento",
      description: "Entregamos documentación completa y seguimiento post-servicio",
    },
  ],
}

export const navigation = [
  { name: "Inicio", href: "#hero" },
  { name: "Servicios", href: "#servicios" },
  { name: "Casos", href: "#casos" },
  { name: "Planes", href: "#planes" },
  { name: "Proceso", href: "#proceso" },
  { name: "Nosotros", href: "#nosotros" },
  { name: "Testimonios", href: "#testimonios" },
  { name: "Contacto", href: "#contacto" },
]
